name: pyembeo
dependencies:
  - python>=3.5
  - faiss-cpu=1.5.3
  - pip
  - pip:
      - pandas==0.25.0
      - setuptools==41.1.0
      - py2neo==5.0b1
      - pyyaml==5.1.2
      - torchbiggraph==1.0.0
channels:
  - pytorch
  - conda-forge
